export const orderData = [
  {
    id: 1,
    restaurantName: "Min Ma Har",
    order: [
      {
        id: 1,
        foodName: "tone yan hta min",
        foodCount: 4,
      },
      {
        id: 2,
        foodName: "pal late khote",
        foodCount: 2,
      },
    ],
    status: "accepted",
    message:
      "please hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    customerName: "Hein Htet Aung",
    address:
      "E-block, E-224 ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    paymentMethod: { method: "kbzpay", additionalInfo: "09776219247" },
    paymentStatus: false,
    phoneNumber: "+95776239247",
    orderState: "order",
    statusDate: "2022-11-27T15:07:02.903Z",
  },
];

export const menuData = [
  {
    id: 1,
    name: "Mala Xiagn",
    nameError: false,
    image: "",
    imageError: false,
    price: 2000,
    priceError: false,
    description: "Upload a selected file using the F",
    category: "curry",
  },
  {
    id: 2,
    name: "hotpot",
    nameError: false,
    image: "",
    imageError: false,
    price: 3000,
    priceError: false,
    description:
      "Upload a selected file using the FormData object. Append the name and file using",
    category: "sideDish",
  },
  {
    id: 3,
    name: "Banana snack",
    nameError: false,
    image: "",
    imageError: false,
    price: 2500,
    priceError: false,
    description:
      "That's pretty much it. You have successfullom file upload componen",
    category: "drink",
  },
  {
    id: 4,
    name: "Pathein Halawar",
    nameError: false,
    image: "",
    imageError: false,
    price: 1500,
    priceError: false,
    description: "asfasrwrweieatjoewitaweoitjaeowitweohto",
    category: "additional",
  },
  {
    id: 5,
    name: "Mala Xiagn",
    nameError: false,
    image: "",
    imageError: false,
    price: 2000,
    priceError: false,
    description: "Upload a selected file using the F",
    category: "curry",
  },
  {
    id: 6,
    name: "Mala Xiagn",
    nameError: false,
    image: "",
    imageError: false,
    price: 2000,
    priceError: false,
    description: "Upload a selected file using the F",
    category: "curry",
  },
  {
    id: 7,
    name: "Mala Xiagn",
    nameError: false,
    image: "",
    imageError: false,
    price: 2000,
    priceError: false,
    description: "Upload a selected file using the F",
    category: "curry",
  },
];

export const restaurantData = [
  {
    id: 1,
    restaurantName: "T-food House",
    phoneNumber: "09777777777",
    additionalPhoneNumber: "09888888888",
    email: "heinh234242@gmail.com",
    address: "Insein Kyokone, Yangon Technological University, Cafeteria",
    establishedIn: 2022,
    availablePaymentMethods: ["KBZPay", "WavePay", "Cash"],
    delivery: false,
  },
  {
    id: 2,
    restaurantName: "Shwe Latt Toe",
    phoneNumber: "097232323232",
    additionalPhoneNumber: "09999999999",
    email: "heinh234242@gmail.com",
    address:
      "Jacks Bar and Kitchen is the brainchild of Ryan and John McElhinney. We are located at 9",
    establishedIn: 2022,
    availablePaymentMethods: ["KBZPay", "WavePay", "Cash"],
    delivery: true,
  },
];
