export const data = [
  {
    name: "chinese fried rice",
    message: "please hurry",
    status: "order received",
    statusDate: new Date(),
    address: "E-block, E-224",
    paymentMethod: "cash of delievery",
    paymentStatus: "Received",
    phoneNumber: "09776219247",
  },
  {
    name: "chinese fried rice",
    message: "please hurry",
    status: "order received",
    statusDate: new Date(),
    address: "E-block, E-224",
    paymentMethod: "cash of delievery",
    paymentStatus: "Received",
    phoneNumber: "09776219247",
  },
  {
    name: "chinese fried rice",
    message: "please hurry",
    status: "order received",
    statusDate: new Date(),
    address: "E-block, E-224",
    paymentMethod: "cash of delievery",
    paymentStatus: "Received",
    phoneNumber: "09776219247",
  },
  {
    name: "chinese fried rice",
    message: "please hurry",
    status: "order received",
    statusDate: new Date(),
    address: "E-block, E-224",
    paymentMethod: "cash of delievery",
    paymentStatus: "Received",
    phoneNumber: "09776219247",
  },
  {
    name: "chinese fried rice",
    message: "please hurry",
    status: "order received",
    statusDate: new Date(),
    address: "E-block, E-224",
    paymentMethod: "cash of delievery",
    paymentStatus: "Received",
    phoneNumber: "09776219247",
  },
  {
    name: "chinese fried rice",
    message: "please hurry",
    status: "order received",
    statusDate: new Date(),
    address: "E-block, E-224",
    paymentMethod: "cash of delievery",
    paymentStatus: "Received",
    phoneNumber: "09776219247",
  },
];
