export const orderData = [
  {
    id: 1,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "received",
    message:
      "please hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Hein Htet Aung",
    address:
      "E-block, E-224 ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    paymentMethod: "kpay(4806)",
    paymentState: false,
    phoneNumber: +95776239247,
    orderState: "order",
  },
  {
    id: 2,
    foodName: "Dan Pout",
    foodCount: 4,
    status: "accepted",
    message:
      "please hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Hein Htet Aung",
    address:
      "E-block, E-224 ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    paymentMethod: "kpay(4806)",
    paymentState: true,
    phoneNumber: +959776219247,
    orderState: "recycleBin",
  },
  {
    id: 3,
    foodName: "Hta Min Paung",
    foodCount: 4,
    status: "onDelivery",
    message: "p can use thler to get the va",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Su Myat",
    address:
      "E-blo.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    paymentMethod: "kpay(4806)",
    paymentState: true,
    phoneNumber: +959776219247,
    orderState: "history",
  },
  {
    id: 4,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "onDelivery",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: false,
    phoneNumber: +959776219247,
    orderState: "history",
  },
  {
    id: 5,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "accepted",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: false,
    phoneNumber: +959776219247,
    orderState: "history",
  },
  {
    id: 6,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "accepted",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +959776219247,
    orderState: "history",
  },
  {
    id: 7,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "received",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +959776219247,
    orderState: "history",
  },
  {
    id: 8,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "received",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +959776219247,
    orderState: "order",
  },
  {
    id: 9,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "accepted",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: false,
    phoneNumber: +959776219247,
    orderState: "order",
  },
  {
    id: 10,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "received",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +959776219247,
    orderState: "order",
  },
  {
    id: 11,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "accepted",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +959776219247,
    orderState: "order",
  },
  {
    id: 12,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "accepted",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: false,
    phoneNumber: +959776219247,
    orderState: "order",
  },
  {
    id: 13,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "received",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: false,
    phoneNumber: +959776219247,
    orderState: "order",
  },
  {
    id: 14,
    foodName: "chicken fried rice",
    foodCount: 4,
    status: "recycleBin",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: false,
    phoneNumber: +959776219247,
    orderState: "order",
  },
  {
    id: 15,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "accepted",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +959776219247,
    orderState: "order",
  },
  {
    id: 16,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "received",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +959776219247,
    orderState: "recycleBin",
  },
  {
    id: 17,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "accepted",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +959776219247,
    orderState: "recycleBin",
  },
  {
    id: 18,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "received",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +959776219247,
    orderState: "recycleBin",
  },
  {
    id: 19,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "received",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: 959776219247,
    orderState: "recycleBin",
  },
  {
    id: 20,
    foodName: "chinese fried rice",
    foodCount: 4,
    status: "onDelivery",
    message:
      "pleasu can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.ease hurryTo fetch the selected value from the select element, you can use the onChange event handler prop. Just like the input or textarea elements, you can use the onChange event handler to get the value from the event object.",
    statusDate: "2022-11-19T03:40:52.975Z",
    customerName: "Shunn",
    address: "E-block, E-224 ease hurryTo fetch the selected v",
    paymentMethod: "kpay(4806)",
    paymentStatus: true,
    phoneNumber: +95776239247,
    orderState: "recycleBin",
  },
];

export const menuData = [
  {
    id: 1,
    name: "Mala Xiagn",
    image: "",
    imageError: false,
    price: 2000,
    description:
      "Upload a selected file using the FormData object. Append the name and file using the append method of the formData object.",
    nameEdit: false,
    priceEdit: false,
    descriptionEdit: false,
    beatOnce: {
      firstBtn: true,
      secondBtn: false,
      thirdBtn: false,
    },
  },
  {
    id: 2,
    name: "hotpot",
    image: "",
    imageError: false,
    price: 3000,
    description:
      "Upload a selected file using the FormData object. Append the name and file using",
    nameEdit: false,
    priceEdit: false,
    descriptionEdit: false,
    beatOnce: {
      firstBtn: true,
      secondBtn: false,
      thirdBtn: false,
    },
  },
  {
    id: 3,
    name: "Banana snack",
    image: "",
    imageError: false,
    price: 2500,
    description:
      "That's pretty much it. You have successfully created and added a custom file upload componen",
    nameEdit: false,
    priceEdit: false,
    descriptionEdit: false,
    beatOnce: {
      firstBtn: true,
      secondBtn: false,
      thirdBtn: false,
    },
  },
  {
    id: 4,
    name: "Pathein Halawar",
    image: "",
    price: 1500,
    description: "asfasrwrweieatjoewitaweoitjaeowitweohto",
    nameEdit: false,
    priceEdit: false,
    descriptionEdit: false,
    beatOnce: {
      firstBtn: true,
      secondBtn: false,
      thirdBtn: false,
    },
  },
];
